# Web Scraping

This notebook will have problems that touch on the material covered in `Lectures/Data Collection/Web Scraping with BeautifulSoup`.

In [1]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
from time import sleep
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import TimeoutException

##### 1. imdb - go to film reviews page in browser

In [ ]:
# open browser
driver = webdriver.Chrome()

In [ ]:
# american history x reviews
# Need to log in after visiting site to get review list for obtaining reviewer URLs
driver.get("https://www.imdb.com/title/tt0120586/reviews/?sort=review_volume%2Cdesc")
#print(title)

In [ ]:
# Load 25 more reviews 3 times
# (Can be modified to get full reviewer list easily)
for i in range(3):
    button = WebDriverWait(driver, 5).until(
            EC.presence_of_element_located((By.CSS_SELECTOR, "button.ipc-see-more__button"))
        )
    #scroll on page to reach button, otherwise click fails
    driver.execute_script("arguments[0].scrollIntoView(true);", button)
    sleep(1)        
    # Click it
    button.click()

In [11]:
soup=BeautifulSoup(driver.page_source, 'html.parser')

In [ ]:
# Previous attempt to find "more reviews" button

#my_button = driver.find_element(By.XPATH, "//span[contains(@class, 'ipc-see-more__text')]//ancestor::button")
##my_button.click()
#driver.implicitly_wait(5)
#my_button.click()

In [ ]:
# Alt wait for button to be clickable
my_button = WebDriverWait(driver, 10).until(
    EC.element_to_be_clickable((By.CSS_SELECTOR, "button.ipc-see-more__button"))
)
my_button.click()

In [13]:
#users = soup.find_all('span', class_="antialiased tracking-[0.02em] !text-sm overflow-hidden text-ellipsis whitespace-nowrap"); users
user_urls = soup.find_all('a', attrs={'data-testid' : 'author-link'}); user_urls
print(len(user_urls))

100

In [14]:
usr_links=[]
for usr in user_urls:
    try:
        uname_raw= usr.find('span',class_="antialiased tracking-[0.02em] !text-sm overflow-hidden text-ellipsis whitespace-nowrap")
        url_raw=usr.get('href').split('?')[0]
        uname=uname_raw.text.strip()
        url = "https://www.imdb.com"+url_raw+'ratings'
        #year=film.find('li',class_="ipc-inline-list__item")
        #rating has two entries, first avg then user
        #rating_text = rating[1].text.strip()
        #get rid of number before the title
        #title_text = title[0].text.split('. ', 1)[1]
        #year_text = year.text.strip()
        print(uname, url)
        usr_links.append({'username': uname, 'ratings_url':url })
    except:
        # Skip if either element is not found in this <li>
        continue

    
usr_links

planktonrules https://www.imdb.com/user/p.twhkadfwuxnnk3v3crk2lbxcda/ratings
SnoopyStyle https://www.imdb.com/user/p.jdpo6uufynnvg5phhb3jhga4ji/ratings
Kirpianuscus https://www.imdb.com/user/p.idvjk25ntslz3t4zlr4bthixra/ratings
mark.waltz https://www.imdb.com/user/p.f3fpx4l7nz7xjpaxcnmbs6mfue/ratings
Sleepin_Dragon https://www.imdb.com/user/p.nadoqibapcutzfhtliuzriogla/ratings
Leofwine_draca https://www.imdb.com/user/p.f772breweshp773tnlaavsxh5m/ratings
Hitchcoc https://www.imdb.com/user/p.bprpogbwb56iaix6ajsznizkde/ratings
paul_m_haakonsen https://www.imdb.com/user/p.jhijfk6m2bldmwgfat3yuhau5m/ratings
ma-cortes https://www.imdb.com/user/p.4ezgnj6y3mutunwrpwjnf35w24/ratings
bob the moo https://www.imdb.com/user/p.5ofp5vs6p3vaea4izrcquut2ni/ratings
classicsoncall https://www.imdb.com/user/p.a2czb7imou26utvw3vyhx7v5vi/ratings
lee_eisenberg https://www.imdb.com/user/p.f6xwteryvnx326x3jn267izo4u/ratings
jboothmillard https://www.imdb.com/user/p.fwftg73zq35i266aiizvm3fikq/ratings
BA_Harrison https://www.imdb.com/user/p.gplkjaqncmrj763al73gvwyq5q/ratings
TxMike https://www.imdb.com/user/p.lwievry4r52hna5jmubgvbxuou/ratings
moonspinner55 https://www.imdb.com/user/p.tplgh6twt3n3han7zik6i6ncxe/ratings
gavin6942 https://www.imdb.com/user/p.ipulzcdf6eohek3d5zte3h6zz4/ratings
SG_TheOriginal https://www.imdb.com/user/p.4dh5taeqxd5w4yjvibdf4stk44/ratings
rmax304823 https://www.imdb.com/user/p.2yxrlaq7eyjukjbnyh3p7cnzie/ratings
fernandoschiavi https://www.imdb.com/user/p.qknnowmiv4evgdrfak3ppkp6ey/ratings
kevin_robbins https://www.imdb.com/user/p.yl3zwh27otxh6saaliek3mymju/ratings
Quinoa1984 https://www.imdb.com/user/p.fulm227xormi6gj7qu4ebnch2q/ratings
AlsExGal https://www.imdb.com/user/p.lk23pc7ndmb4vvqniu34jn63b4/ratings
grantss https://www.imdb.com/user/p.tv3lbo62mcydib7clf22mh67am/ratings
michaelRokeefe https://www.imdb.com/user/p.skh75kvktqntorqae3fxdg45ra/ratings
view_and_review https://www.imdb.com/user/p.3rebozhwiyihuqgr67o2biwqhm/ratings
LeonLouisRicci https://www.imdb.com/user/p.k7xeaefno4aadrhjdnm7ntuij4/ratings
tedg https://www.imdb.com/user/p.bc2j7zuvjvhw63jyryvqisakwy/ratings
Theo Robertson https://www.imdb.com/user/p.u4cs2ki2zvfyc4xxjhr6kjw2x4/ratings
preppy-3 https://www.imdb.com/user/p.ju5d5mjw3qkffeuvfzxy3we5ni/ratings
evanston_dad https://www.imdb.com/user/p.gs4yhdts4m2wdidac5xw7vknza/ratings
bevo-13678 https://www.imdb.com/user/p.rkhmrao6fuxalpsmgsixfrkmz4/ratings
Wuchakk https://www.imdb.com/user/p.mao7ywusxuxb4lweznfe2uq4ne/ratings
TBJCSKCNRRQTreviews https://www.imdb.com/user/p.m3calhbigskm7rxxvn3cyrpe3a/ratings
Pjtaylor-96-138044 https://www.imdb.com/user/p.i6gwpf7avt2lbtga3fpughngui/ratings
Boba_Fett1138 https://www.imdb.com/user/p.sxnewop2aw4y4wi2zza46upd3i/ratings
george.schmidt https://www.imdb.com/user/p.66remrvxwyaxs5gazqvpdsypeu/ratings
paulclaassen https://www.imdb.com/user/p.nojzgfjbgh22fdkzbt5l6ltnuy/ratings
Sylviastel https://www.imdb.com/user/p.735egksadulahjaezd6ynic3pa/ratings
FeastMode https://www.imdb.com/user/p.ef46gx7rv5scj76nzdfcf2sche/ratings
JamesHitchcock https://www.imdb.com/user/p.u4dkl5vgtepgq7vpk53f6gak3u/ratings
Mr-Fusion https://www.imdb.com/user/p.bnlwn6muaqewgdbh6gfyiosqoe/ratings
arthur_tafero https://www.imdb.com/user/p.jdkd4mh54kbs5n52s4jpxosrwm/ratings
imseeg https://www.imdb.com/user/p.bqt66ijjj64wfs7pbdawlvv5ym/ratings
dromasca https://www.imdb.com/user/p.3uq53idyzk4wg3rzb47yl637uy/ratings
thesar-2 https://www.imdb.com/user/p.mbwqx75yvbk2vxexypjqh66a7a/ratings
paul2001sw-1 https://www.imdb.com/user/p.o5icsyzyfih4qc7jcgiho5nirq/ratings
cinemasauron https://www.imdb.com/user/p.hdivet24xt6ljeq23kljxvctiq/ratings
wellthatswhatithinkanyway https://www.imdb.com/user/p.2oa2dfvnuu7a76m3vkilxj66ce/ratings
Vincentiu https://www.imdb.com/user/p.whhgi5cvtcwo2iln4v4t5rndny/ratings
sddavis63 https://www.imdb.com/user/p.xoer4dcohv3jssbymc456a3bve/ratings
whpratt1 https://www.imdb.com/user/p.nillss5pj4j7txflninlvrekfm/ratings
Thanos_Alfie https://www.imdb.com/user/p.7my7pjdrp2lqjgeratvtilxpcq/ratings
namashi_1 https://www.imdb.com/user/p.rrtddk7vf67hnq5plpoxcm6kyu/ratings
ChaseWitherspoon75 https://www.imdb.com/user/p.izy5xoobgqxduvkloh2cj5t3ua/ratings
filipemanuelneto https://www.imdb.com/user/p.z67hstlsoxaqkok2uct6p32sdi/ratings
Smells_Like_Cheese https://www.imdb.com/user/p.ssqtupaepb2pbvfb2v7udr6oc4/ratings
ElMaruecan82 https://www.imdb.com/user/p.6ydvic4ngubynjfrjokpzm3jky/ratings
martinpersson97 https://www.imdb.com/user/p.c3oohrd4k45ds3krinbt7ermye/ratings
jack_hasanov https://www.imdb.com/user/p.pa4yspevrs4giwserxsumraahy/ratings
MovieAddict2016 https://www.imdb.com/user/p.h3dtcl66i3cm63ebmi6lul3ere/ratings
disdressed12 https://www.imdb.com/user/p.h7ip4jkhdcd3blzu5j5ozpe6rm/ratings
damianphelps https://www.imdb.com/user/p.bfkwoqos7nqe3mom5z6pytjtci/ratings
fredrikgunerius https://www.imdb.com/user/p.3j3f44zbvlitymvvrynddm7isq/ratings
eddie_baggins https://www.imdb.com/user/p.wftsft6prw3merfqddjjvts5ky/ratings
briancham1994 https://www.imdb.com/user/p.nqjqabbaendjklsiw2hvvalnu4/ratings
Giugi1101 https://www.imdb.com/user/p.3zc6durvpwzpg4sdhsek533abm/ratings
Top_Dawg_Critic https://www.imdb.com/user/p.byjvbpzuua5oseqhyhaajr2tlu/ratings
Bored_Dragon https://www.imdb.com/user/p.brtlrmz6i2xqqevkzrayctuege/ratings
g-bodyl https://www.imdb.com/user/p.2yagong2sdy5zhyqgv4btjtxky/ratings
tfrizzell https://www.imdb.com/user/p.dc6inx7y3hlx757rlproqvr2la/ratings
secondtake https://www.imdb.com/user/p.jbpgz4ixsfwjhg43wk67o4otpy/ratings
lesleyharris30 https://www.imdb.com/user/p.ftz62bzlrx2nrqjqsb7ie4mre4/ratings
nairtejas https://www.imdb.com/user/p.lphta7eusup6uh6lbzu2tdrc4q/ratings
kenjha https://www.imdb.com/user/p.wuu7az4y2sz7o6wxtgu5ou7f6q/ratings
jgcorrea https://www.imdb.com/user/p.z3d2uqkyif3q3kj5okvo4doo4i/ratings
Dr_Coulardeau https://www.imdb.com/user/p.bbmh4tcx4ppfify4owyaa7w4bi/ratings
tomgillespie2002 https://www.imdb.com/user/p.an3jwh7ieevwu5udeprw5ll24q/ratings
billcr12 https://www.imdb.com/user/p.tlg3z5l6dzs3rc62yb5y77b76a/ratings
MovieswithMacca https://www.imdb.com/user/p.uwvknowhsvoofhwvilnyblrowq/ratings
johnnyboyz https://www.imdb.com/user/p.smyvhp6nrepzne7z6ptgabyh3e/ratings
Special-K88 https://www.imdb.com/user/p.5qlfd4zhtlhbvvfteyidh63wde/ratings
leplatypus https://www.imdb.com/user/p.fwo77z6me2y3v5z2uvff6qj6si/ratings
insomniac_rod https://www.imdb.com/user/p.sfucxjruq4rbe5k6upsvz2obmi/ratings
marmar-69780 https://www.imdb.com/user/p.scxvwblywgbaomphxft5cwt254/ratings
Movie_Muse_Reviews https://www.imdb.com/user/p.7c3fgrdyd3fdfkopdnsa66i324/ratings
robert-temple-1 https://www.imdb.com/user/p.2awhusdkssv7degnis3kn5wuqy/ratings
Anonymous_Maxine https://www.imdb.com/user/p.azbj2ipwoioeuuyy5poa7ygbqu/ratings
freemantle_uk https://www.imdb.com/user/p.qym4c27lh66u3cp36ove36ucsq/ratings
Vartiainen https://www.imdb.com/user/p.fno67lqfncedcpsgy6sjcten6y/ratings
dworldeater https://www.imdb.com/user/p.iopux7uexupdhiberqsmhqop2u/ratings
dee.reid https://www.imdb.com/user/p.mmfduh32vdru2mi2gbrvv345wi/ratings
jfgibson73 https://www.imdb.com/user/p.vitpvwogqalh7fqq3hevoicmnq/ratings
smatysia https://www.imdb.com/user/p.a7mhntekc5uwtzfe2x6yjdlyxa/ratings
evening1 https://www.imdb.com/user/p.sraeoqsjk775szlpgx7ntx7w34/ratings
SPZMaxinema https://www.imdb.com/user/p.nu4mr4jblyof24vb6baowls4ru/ratings
akshatmahajan https://www.imdb.com/user/p.hpey7kijqvc7fp2qxtijoked7u/ratings
JayWolfgramm https://www.imdb.com/user/p.lip7djvncpjjdz3u2hofjfnwhm/ratings
juneebuggy https://www.imdb.com/user/p.pzgwbnuduygrcweijr2usgxwkm/ratings
TaylorYee94 https://www.imdb.com/user/p.luncv7q6qle2ecxuyit52egbve/ratings

[{'username': 'planktonrules',
  'ratings_url': 'https://www.imdb.com/user/p.twhkadfwuxnnk3v3crk2lbxcda/ratings'},
 {'username': 'SnoopyStyle',
  'ratings_url': 'https://www.imdb.com/user/p.jdpo6uufynnvg5phhb3jhga4ji/ratings'},
 {'username': 'Kirpianuscus',
  'ratings_url': 'https://www.imdb.com/user/p.idvjk25ntslz3t4zlr4bthixra/ratings'},
 {'username': 'mark.waltz',
  'ratings_url': 'https://www.imdb.com/user/p.f3fpx4l7nz7xjpaxcnmbs6mfue/ratings'},
 {'username': 'Sleepin_Dragon',
  'ratings_url': 'https://www.imdb.com/user/p.nadoqibapcutzfhtliuzriogla/ratings'},
 {'username': 'Leofwine_draca',
  'ratings_url': 'https://www.imdb.com/user/p.f772breweshp773tnlaavsxh5m/ratings'},
 {'username': 'Hitchcoc',
  'ratings_url': 'https://www.imdb.com/user/p.bprpogbwb56iaix6ajsznizkde/ratings'},
 {'username': 'paul_m_haakonsen',
  'ratings_url': 'https://www.imdb.com/user/p.jhijfk6m2bldmwgfat3yuhau5m/ratings'},
 {'username': 'ma-cortes',
  'ratings_url': 'https://www.imdb.com/user/p.4ezgnj6y3mutunwrpwjnf35w24/ratings'},
 {'username': 'bob the moo',
  'ratings_url': 'https://www.imdb.com/user/p.5ofp5vs6p3vaea4izrcquut2ni/ratings'},
 {'username': 'classicsoncall',
  'ratings_url': 'https://www.imdb.com/user/p.a2czb7imou26utvw3vyhx7v5vi/ratings'},
 {'username': 'lee_eisenberg',
  'ratings_url': 'https://www.imdb.com/user/p.f6xwteryvnx326x3jn267izo4u/ratings'},
 {'username': 'jboothmillard',
  'ratings_url': 'https://www.imdb.com/user/p.fwftg73zq35i266aiizvm3fikq/ratings'},
 {'username': 'BA_Harrison',
  'ratings_url': 'https://www.imdb.com/user/p.gplkjaqncmrj763al73gvwyq5q/ratings'},
 {'username': 'TxMike',
  'ratings_url': 'https://www.imdb.com/user/p.lwievry4r52hna5jmubgvbxuou/ratings'},
 {'username': 'moonspinner55',
  'ratings_url': 'https://www.imdb.com/user/p.tplgh6twt3n3han7zik6i6ncxe/ratings'},
 {'username': 'gavin6942',
  'ratings_url': 'https://www.imdb.com/user/p.ipulzcdf6eohek3d5zte3h6zz4/ratings'},
 {'username': 'SG_TheOriginal',
  'ratings_url': 'https://www.imdb.com/user/p.4dh5taeqxd5w4yjvibdf4stk44/ratings'},
 {'username': 'rmax304823',
  'ratings_url': 'https://www.imdb.com/user/p.2yxrlaq7eyjukjbnyh3p7cnzie/ratings'},
 {'username': 'fernandoschiavi',
  'ratings_url': 'https://www.imdb.com/user/p.qknnowmiv4evgdrfak3ppkp6ey/ratings'},
 {'username': 'kevin_robbins',
  'ratings_url': 'https://www.imdb.com/user/p.yl3zwh27otxh6saaliek3mymju/ratings'},
 {'username': 'Quinoa1984',
  'ratings_url': 'https://www.imdb.com/user/p.fulm227xormi6gj7qu4ebnch2q/ratings'},
 {'username': 'AlsExGal',
  'ratings_url': 'https://www.imdb.com/user/p.lk23pc7ndmb4vvqniu34jn63b4/ratings'},
 {'username': 'grantss',
  'ratings_url': 'https://www.imdb.com/user/p.tv3lbo62mcydib7clf22mh67am/ratings'},
 {'username': 'michaelRokeefe',
  'ratings_url': 'https://www.imdb.com/user/p.skh75kvktqntorqae3fxdg45ra/ratings'},
 {'username': 'view_and_review',
  'ratings_url': 'https://www.imdb.com/user/p.3rebozhwiyihuqgr67o2biwqhm/ratings'},
 {'username': 'LeonLouisRicci',
  'ratings_url': 'https://www.imdb.com/user/p.k7xeaefno4aadrhjdnm7ntuij4/ratings'},
 {'username': 'tedg',
  'ratings_url': 'https://www.imdb.com/user/p.bc2j7zuvjvhw63jyryvqisakwy/ratings'},
 {'username': 'Theo Robertson',
  'ratings_url': 'https://www.imdb.com/user/p.u4cs2ki2zvfyc4xxjhr6kjw2x4/ratings'},
 {'username': 'preppy-3',
  'ratings_url': 'https://www.imdb.com/user/p.ju5d5mjw3qkffeuvfzxy3we5ni/ratings'},
 {'username': 'evanston_dad',
  'ratings_url': 'https://www.imdb.com/user/p.gs4yhdts4m2wdidac5xw7vknza/ratings'},
 {'username': 'bevo-13678',
  'ratings_url': 'https://www.imdb.com/user/p.rkhmrao6fuxalpsmgsixfrkmz4/ratings'},
 {'username': 'Wuchakk',
  'ratings_url': 'https://www.imdb.com/user/p.mao7ywusxuxb4lweznfe2uq4ne/ratings'},
 {'username': 'TBJCSKCNRRQTreviews',
  'ratings_url': 'https://www.imdb.com/user/p.m3calhbigskm7rxxvn3cyrpe3a/ratings'},
 {'username': 'Pjtaylor-96-138044',
  'ratings_url': 'https://www.imdb.com/user/p.i6gwpf7avt2lbtga3fpughngui/ratings'},
 {'username': 'Boba_Fett1138',
  'ratings_url': 'https://www.imdb.com/user/p.sxnewop2aw4y4wi2zza46upd3i/ratings'},
 {'username': 'george.schmidt',
  'ratings_url': 'https://www.imdb.com/user/p.66remrvxwyaxs5gazqvpdsypeu/ratings'},
 {'username': 'paulclaassen',
  'ratings_url': 'https://www.imdb.com/user/p.nojzgfjbgh22fdkzbt5l6ltnuy/ratings'},
 {'username': 'Sylviastel',
  'ratings_url': 'https://www.imdb.com/user/p.735egksadulahjaezd6ynic3pa/ratings'},
 {'username': 'FeastMode',
  'ratings_url': 'https://www.imdb.com/user/p.ef46gx7rv5scj76nzdfcf2sche/ratings'},
 {'username': 'JamesHitchcock',
  'ratings_url': 'https://www.imdb.com/user/p.u4dkl5vgtepgq7vpk53f6gak3u/ratings'},
 {'username': 'Mr-Fusion',
  'ratings_url': 'https://www.imdb.com/user/p.bnlwn6muaqewgdbh6gfyiosqoe/ratings'},
 {'username': 'arthur_tafero',
  'ratings_url': 'https://www.imdb.com/user/p.jdkd4mh54kbs5n52s4jpxosrwm/ratings'},
 {'username': 'imseeg',
  'ratings_url': 'https://www.imdb.com/user/p.bqt66ijjj64wfs7pbdawlvv5ym/ratings'},
 {'username': 'dromasca',
  'ratings_url': 'https://www.imdb.com/user/p.3uq53idyzk4wg3rzb47yl637uy/ratings'},
 {'username': 'thesar-2',
  'ratings_url': 'https://www.imdb.com/user/p.mbwqx75yvbk2vxexypjqh66a7a/ratings'},
 {'username': 'paul2001sw-1',
  'ratings_url': 'https://www.imdb.com/user/p.o5icsyzyfih4qc7jcgiho5nirq/ratings'},
 {'username': 'cinemasauron',
  'ratings_url': 'https://www.imdb.com/user/p.hdivet24xt6ljeq23kljxvctiq/ratings'},
 {'username': 'wellthatswhatithinkanyway',
  'ratings_url': 'https://www.imdb.com/user/p.2oa2dfvnuu7a76m3vkilxj66ce/ratings'},
 {'username': 'Vincentiu',
  'ratings_url': 'https://www.imdb.com/user/p.whhgi5cvtcwo2iln4v4t5rndny/ratings'},
 {'username': 'sddavis63',
  'ratings_url': 'https://www.imdb.com/user/p.xoer4dcohv3jssbymc456a3bve/ratings'},
 {'username': 'whpratt1',
  'ratings_url': 'https://www.imdb.com/user/p.nillss5pj4j7txflninlvrekfm/ratings'},
 {'username': 'Thanos_Alfie',
  'ratings_url': 'https://www.imdb.com/user/p.7my7pjdrp2lqjgeratvtilxpcq/ratings'},
 {'username': 'namashi_1',
  'ratings_url': 'https://www.imdb.com/user/p.rrtddk7vf67hnq5plpoxcm6kyu/ratings'},
 {'username': 'ChaseWitherspoon75',
  'ratings_url': 'https://www.imdb.com/user/p.izy5xoobgqxduvkloh2cj5t3ua/ratings'},
 {'username': 'filipemanuelneto',
  'ratings_url': 'https://www.imdb.com/user/p.z67hstlsoxaqkok2uct6p32sdi/ratings'},
 {'username': 'Smells_Like_Cheese',
  'ratings_url': 'https://www.imdb.com/user/p.ssqtupaepb2pbvfb2v7udr6oc4/ratings'},
 {'username': 'ElMaruecan82',
  'ratings_url': 'https://www.imdb.com/user/p.6ydvic4ngubynjfrjokpzm3jky/ratings'},
 {'username': 'martinpersson97',
  'ratings_url': 'https://www.imdb.com/user/p.c3oohrd4k45ds3krinbt7ermye/ratings'},
 {'username': 'jack_hasanov',
  'ratings_url': 'https://www.imdb.com/user/p.pa4yspevrs4giwserxsumraahy/ratings'},
 {'username': 'MovieAddict2016',
  'ratings_url': 'https://www.imdb.com/user/p.h3dtcl66i3cm63ebmi6lul3ere/ratings'},
 {'username': 'disdressed12',
  'ratings_url': 'https://www.imdb.com/user/p.h7ip4jkhdcd3blzu5j5ozpe6rm/ratings'},
 {'username': 'damianphelps',
  'ratings_url': 'https://www.imdb.com/user/p.bfkwoqos7nqe3mom5z6pytjtci/ratings'},
 {'username': 'fredrikgunerius',
  'ratings_url': 'https://www.imdb.com/user/p.3j3f44zbvlitymvvrynddm7isq/ratings'},
 {'username': 'eddie_baggins',
  'ratings_url': 'https://www.imdb.com/user/p.wftsft6prw3merfqddjjvts5ky/ratings'},
 {'username': 'briancham1994',
  'ratings_url': 'https://www.imdb.com/user/p.nqjqabbaendjklsiw2hvvalnu4/ratings'},
 {'username': 'Giugi1101',
  'ratings_url': 'https://www.imdb.com/user/p.3zc6durvpwzpg4sdhsek533abm/ratings'},
 {'username': 'Top_Dawg_Critic',
  'ratings_url': 'https://www.imdb.com/user/p.byjvbpzuua5oseqhyhaajr2tlu/ratings'},
 {'username': 'Bored_Dragon',
  'ratings_url': 'https://www.imdb.com/user/p.brtlrmz6i2xqqevkzrayctuege/ratings'},
 {'username': 'g-bodyl',
  'ratings_url': 'https://www.imdb.com/user/p.2yagong2sdy5zhyqgv4btjtxky/ratings'},
 {'username': 'tfrizzell',
  'ratings_url': 'https://www.imdb.com/user/p.dc6inx7y3hlx757rlproqvr2la/ratings'},
 {'username': 'secondtake',
  'ratings_url': 'https://www.imdb.com/user/p.jbpgz4ixsfwjhg43wk67o4otpy/ratings'},
 {'username': 'lesleyharris30',
  'ratings_url': 'https://www.imdb.com/user/p.ftz62bzlrx2nrqjqsb7ie4mre4/ratings'},
 {'username': 'nairtejas',
  'ratings_url': 'https://www.imdb.com/user/p.lphta7eusup6uh6lbzu2tdrc4q/ratings'},
 {'username': 'kenjha',
  'ratings_url': 'https://www.imdb.com/user/p.wuu7az4y2sz7o6wxtgu5ou7f6q/ratings'},
 {'username': 'jgcorrea',
  'ratings_url': 'https://www.imdb.com/user/p.z3d2uqkyif3q3kj5okvo4doo4i/ratings'},
 {'username': 'Dr_Coulardeau',
  'ratings_url': 'https://www.imdb.com/user/p.bbmh4tcx4ppfify4owyaa7w4bi/ratings'},
 {'username': 'tomgillespie2002',
  'ratings_url': 'https://www.imdb.com/user/p.an3jwh7ieevwu5udeprw5ll24q/ratings'},
 {'username': 'billcr12',
  'ratings_url': 'https://www.imdb.com/user/p.tlg3z5l6dzs3rc62yb5y77b76a/ratings'},
 {'username': 'MovieswithMacca',
  'ratings_url': 'https://www.imdb.com/user/p.uwvknowhsvoofhwvilnyblrowq/ratings'},
 {'username': 'johnnyboyz',
  'ratings_url': 'https://www.imdb.com/user/p.smyvhp6nrepzne7z6ptgabyh3e/ratings'},
 {'username': 'Special-K88',
  'ratings_url': 'https://www.imdb.com/user/p.5qlfd4zhtlhbvvfteyidh63wde/ratings'},
 {'username': 'leplatypus',
  'ratings_url': 'https://www.imdb.com/user/p.fwo77z6me2y3v5z2uvff6qj6si/ratings'},
 {'username': 'insomniac_rod',
  'ratings_url': 'https://www.imdb.com/user/p.sfucxjruq4rbe5k6upsvz2obmi/ratings'},
 {'username': 'marmar-69780',
  'ratings_url': 'https://www.imdb.com/user/p.scxvwblywgbaomphxft5cwt254/ratings'},
 {'username': 'Movie_Muse_Reviews',
  'ratings_url': 'https://www.imdb.com/user/p.7c3fgrdyd3fdfkopdnsa66i324/ratings'},
 {'username': 'robert-temple-1',
  'ratings_url': 'https://www.imdb.com/user/p.2awhusdkssv7degnis3kn5wuqy/ratings'},
 {'username': 'Anonymous_Maxine',
  'ratings_url': 'https://www.imdb.com/user/p.azbj2ipwoioeuuyy5poa7ygbqu/ratings'},
 {'username': 'freemantle_uk',
  'ratings_url': 'https://www.imdb.com/user/p.qym4c27lh66u3cp36ove36ucsq/ratings'},
 {'username': 'Vartiainen',
  'ratings_url': 'https://www.imdb.com/user/p.fno67lqfncedcpsgy6sjcten6y/ratings'},
 {'username': 'dworldeater',
  'ratings_url': 'https://www.imdb.com/user/p.iopux7uexupdhiberqsmhqop2u/ratings'},
 {'username': 'dee.reid',
  'ratings_url': 'https://www.imdb.com/user/p.mmfduh32vdru2mi2gbrvv345wi/ratings'},
 {'username': 'jfgibson73',
  'ratings_url': 'https://www.imdb.com/user/p.vitpvwogqalh7fqq3hevoicmnq/ratings'},
 {'username': 'smatysia',
  'ratings_url': 'https://www.imdb.com/user/p.a7mhntekc5uwtzfe2x6yjdlyxa/ratings'},
 {'username': 'evening1',
  'ratings_url': 'https://www.imdb.com/user/p.sraeoqsjk775szlpgx7ntx7w34/ratings'},
 {'username': 'SPZMaxinema',
  'ratings_url': 'https://www.imdb.com/user/p.nu4mr4jblyof24vb6baowls4ru/ratings'},
 {'username': 'akshatmahajan',
  'ratings_url': 'https://www.imdb.com/user/p.hpey7kijqvc7fp2qxtijoked7u/ratings'},
 {'username': 'JayWolfgramm',
  'ratings_url': 'https://www.imdb.com/user/p.lip7djvncpjjdz3u2hofjfnwhm/ratings'},
 {'username': 'juneebuggy',
  'ratings_url': 'https://www.imdb.com/user/p.pzgwbnuduygrcweijr2usgxwkm/ratings'},
 {'username': 'TaylorYee94',
  'ratings_url': 'https://www.imdb.com/user/p.luncv7q6qle2ecxuyit52egbve/ratings'}]

# Combine ratings function with user list above

In [ ]:
def user_rev_250(usr):
    #usr will be a dictionary consisting of {'username': 'blah_1',
    #  'ratings_url: 'https://www.imdb.com/user/p.twhkadfwuxnnk3v3crk2lbxcda/ratings'}, e.g
    uname= usr['username']
    url=usr['ratings_url']
    driver = webdriver.Chrome()
    url+="?sort=num_votes%2Cdesc"
    driver.get(url)
    usr_ratings=[]
    my_button = WebDriverWait(driver, 10).until(
    EC.presence_of_element_located((By.CSS_SELECTOR, "button.ipc-responsive-button"))
)
    ################3#for i in range(4):
    soup=BeautifulSoup(driver.page_source, 'html.parser')
    films = soup.find_all('li', class_="ipc-metadata-list-summary-item"); films
    ##################################
    # for each chunk of 250 films, we get year and title and add to usr_ratings 
    for film in films:
        try:
            rating=film.find_all('span',class_="ipc-rating-star--rating")
            title=film.find_all('h4',class_="ipc-title__text")
            year=film.find('li',class_="ipc-inline-list__item")
            #rating has two entries, first avg then user
            rating_text = rating[1].text.strip()
            #get rid of number before the title
            title_text = title[0].text.split('. ', 1)[1]
            year_text = year.text.strip()
            usr_ratings.append({'title': title_text, 'year': year_text, 'user': uname, 'rating': rating_text})
        except:
            # Skip if either element is not found in this <li>
            continue
    ### IGNORE -- attmpt to load more reviews
    #button = WebDriverWait(driver, 5).until(EC.presence_of_element_located((By.CSS_SELECTOR, "button.ipc-responsive-button")))
        #scroll on page to reach button, otherwise click fails
    #    driver.execute_script("arguments[0].scrollIntoView(true);", button)
    #    sleep(1)        
        # Click it
    #    button.click()
    df=pd.DataFrame(usr_ratings)
    driver.close()
    return df

In [ ]:
# create empty data frame to populate
big_df=pd.DataFrame(columns=['title', 'year', 'user', 'rating']);

In [ ]:
# small scale test to see how code works
for i in range(4):
    try:
        dfu=user_rev_250(usr_links[i])
        print(dfu)
        big_df=pd.concat([big_df,dfu], ignore_index=True)
    except:
        continue

big_df

[{'title': 'The Shawshank Redemption', 'year': '1994', 'user': 'planktonrules', 'rating': '10'}, {'title': 'The Dark Knight', 'year': '2008', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Inception', 'year': '2010', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Fight Club', 'year': '1999', 'user': 'planktonrules', 'rating': '6'}, {'title': 'Interstellar', 'year': '2014', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Forrest Gump', 'year': '1994', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Pulp Fiction', 'year': '1994', 'user': 'planktonrules', 'rating': '10'}, {'title': 'The Matrix', 'year': '1999', 'user': 'planktonrules', 'rating': '7'}, {'title': 'The Godfather', 'year': '1972', 'user': 'planktonrules', 'rating': '10'}, {'title': 'The Lord of the Rings: The Fellowship of the Ring', 'year': '2001', 'user': 'planktonrules', 'rating': '10'}, {'title': 'The Lord of the Rings: The Return of the King', 'year': '2003', 'user': 'planktonrules', 'rating': '10'}, {'title': 'Seven', 'year': '1995', 'user': 'planktonrules', 'rating': '9'}, {'title': 'The Dark Knight Rises', 'year': '2012', 'user': 'planktonrules', 'rating': '7'}, {'title': 'The Lord of the Rings: The Two Towers', 'year': '2002', 'user': 'planktonrules', 'rating': '10'}, {'title': 'Django Unchained', 'year': '2012', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Gladiator', 'year': '2000', 'user': 'planktonrules', 'rating': '8'}, {'title': 'The Wolf of Wall Street', 'year': '2013', 'user': 'planktonrules', 'rating': '5'}, {'title': 'Inglourious Basterds', 'year': '2009', 'user': 'planktonrules', 'rating': '8'}, {'title': 'The Silence of the Lambs', 'year': '1991', 'user': 'planktonrules', 'rating': '7'}, {'title': 'Batman Begins', 'year': '2005', 'user': 'planktonrules', 'rating': '7'}, {'title': 'Stranger Things', 'year': '2016–2025', 'user': 'planktonrules', 'rating': '10'}, {'title': 'Shutter Island', 'year': '2010', 'user': 'planktonrules', 'rating': '9'}, {'title': 'The Prestige', 'year': '2006', 'user': 'planktonrules', 'rating': '7'}, {'title': "Schindler's List", 'year': '1993', 'user': 'planktonrules', 'rating': '10'}, {'title': 'Star Wars: Episode IV - A New Hope', 'year': '1977', 'user': 'planktonrules', 'rating': '10'}, {'title': 'The Avengers', 'year': '2012', 'user': 'planktonrules', 'rating': '7'}, {'title': 'The Departed', 'year': '2006', 'user': 'planktonrules', 'rating': '7'}, {'title': 'Star Wars: Episode V - The Empire Strikes Back', 'year': '1980', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Avatar', 'year': '2009', 'user': 'planktonrules', 'rating': '9'}, {'title': 'The Godfather Part II', 'year': '1974', 'user': 'planktonrules', 'rating': '10'}, {'title': 'Back to the Future', 'year': '1985', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Memento', 'year': '2000', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Titanic', 'year': '1997', 'user': 'planktonrules', 'rating': '9'}, {'title': 'GoodFellas', 'year': '1990', 'user': 'planktonrules', 'rating': '4'}, {'title': 'The Truman Show', 'year': '1998', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Guardians of the Galaxy', 'year': '2014', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Léon: The Professional', 'year': '1994', 'user': 'planktonrules', 'rating': '7'}, {'title': 'WALL·E', 'year': '2008', 'user': 'planktonrules', 'rating': '7'}, {'title': 'Kill Bill: Vol. 1', 'year': '2003', 'user': 'planktonrules', 'rating': '10'}, {'title': 'Terminator 2: Judgment Day', 'year': '1991', 'user': 'planktonrules', 'rating': '9'}, {'title': 'American Beauty', 'year': '1999', 'user': 'planktonrules', 'rating': '8'}, {'title': 'American History X', 'year': '1998', 'user': 'planktonrules', 'rating': '9'}, {'title': 'The Lion King', 'year': '1994', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Deadpool', 'year': '2016', 'user': 'planktonrules', 'rating': '7'}, {'title': 'V for Vendetta', 'year': '2005', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Catch Me If You Can', 'year': '2002', 'user': 'planktonrules', 'rating': '7'}, {'title': 'The Usual Suspects', 'year': '1995', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Up', 'year': '2009', 'user': 'planktonrules', 'rating': '10'}, {'title': 'The Shining', 'year': '1980', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Iron Man', 'year': '2008', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Good Will Hunting', 'year': '1997', 'user': 'planktonrules', 'rating': '5'}, {'title': 'Star Wars: Episode VI - Return of the Jedi', 'year': '1983', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Finding Nemo', 'year': '2003', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Mad Max: Fury Road', 'year': '2015', 'user': 'planktonrules', 'rating': '8'}, {'title': 'No Country for Old Men', 'year': '2007', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Eternal Sunshine of the Spotless Mind', 'year': '2004', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Jurassic Park', 'year': '1993', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Toy Story', 'year': '1995', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Gone Girl', 'year': '2014', 'user': 'planktonrules', 'rating': '7'}, {'title': 'Parasite', 'year': '2019', 'user': 'planktonrules', 'rating': '6'}, {'title': 'Reservoir Dogs', 'year': '1992', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Braveheart', 'year': '1995', 'user': 'planktonrules', 'rating': '7'}, {'title': 'Whiplash', 'year': '2014', 'user': 'planktonrules', 'rating': '9'}, {'title': "One Flew Over the Cuckoo's Nest", 'year': '1975', 'user': 'planktonrules', 'rating': '10'}, {'title': 'The Sixth Sense', 'year': '1999', 'user': 'planktonrules', 'rating': '10'}, {'title': 'Raiders of the Lost Ark', 'year': '1981', 'user': 'planktonrules', 'rating': '9'}, {'title': 'The Hunger Games', 'year': '2012', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Monsters, Inc.', 'year': '2001', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Alien', 'year': '1979', 'user': 'planktonrules', 'rating': '10'}, {'title': 'Dune: Part One', 'year': '2021', 'user': 'planktonrules', 'rating': '7'}, {'title': 'A Beautiful Mind', 'year': '2001', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Oppenheimer', 'year': '2023', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Die Hard', 'year': '1988', 'user': 'planktonrules', 'rating': '9'}, {'title': 'The Intouchables', 'year': '2011', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Taxi Driver', 'year': '1976', 'user': 'planktonrules', 'rating': '5'}, {'title': 'Star Wars: Episode VII - The Force Awakens', 'year': '2015', 'user': 'planktonrules', 'rating': '10'}, {'title': 'Scarface', 'year': '1983', 'user': 'planktonrules', 'rating': '3'}, {'title': 'The Martian', 'year': '2015', 'user': 'planktonrules', 'rating': '10'}, {'title': 'The Terminator', 'year': '1984', 'user': 'planktonrules', 'rating': '10'}, {'title': '12 Angry Men', 'year': '1957', 'user': 'planktonrules', 'rating': '10'}, {'title': 'Snatch', 'year': '2000', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Requiem for a Dream', 'year': '2000', 'user': 'planktonrules', 'rating': '10'}, {'title': 'Toy Story 3', 'year': '2010', 'user': 'planktonrules', 'rating': '8'}, {'title': 'The Grand Budapest Hotel', 'year': '2014', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Spirited Away', 'year': '2001', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Captain America: The First Avenger', 'year': '2011', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Iron Man 3', 'year': '2013', 'user': 'planktonrules', 'rating': '7'}, {'title': 'Thor', 'year': '2011', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Once Upon a Time in... Hollywood', 'year': '2019', 'user': 'planktonrules', 'rating': '6'}, {'title': 'Ratatouille', 'year': '2007', 'user': 'planktonrules', 'rating': '10'}, {'title': 'Iron Man 2', 'year': '2010', 'user': 'planktonrules', 'rating': '5'}, {'title': 'Prisoners', 'year': '2013', 'user': 'planktonrules', 'rating': '10'}, {'title': 'A Clockwork Orange', 'year': '1971', 'user': 'planktonrules', 'rating': '7'}, {'title': 'The Hangover', 'year': '2009', 'user': 'planktonrules', 'rating': '3'}, {'title': 'Star Wars: Episode III - Revenge of the Sith', 'year': '2005', 'user': 'planktonrules', 'rating': '4'}, {'title': 'Inside Out', 'year': '2015', 'user': 'planktonrules', 'rating': '9'}, {'title': 'The Big Lebowski', 'year': '1998', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Donnie Darko', 'year': '2001', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Black Panther', 'year': '2018', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Slumdog Millionaire', 'year': '2008', 'user': 'planktonrules', 'rating': '9'}, {'title': 'The Incredibles', 'year': '2004', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Gravity', 'year': '2013', 'user': 'planktonrules', 'rating': '10'}, {'title': 'How to Train Your Dragon', 'year': '2010', 'user': 'planktonrules', 'rating': '10'}, {'title': 'The Good, the Bad and the Ugly', 'year': '1966', 'user': 'planktonrules', 'rating': '10'}, {'title': 'Black Swan', 'year': '2010', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Blade Runner', 'year': '1982', 'user': 'planktonrules', 'rating': '6'}, {'title': 'Knives Out', 'year': '2019', 'user': 'planktonrules', 'rating': '9'}, {'title': 'I Am Legend', 'year': '2007', 'user': 'planktonrules', 'rating': '6'}, {'title': 'City of God', 'year': '2002', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Kill Bill: Vol. 2', 'year': '2004', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Arrival', 'year': '2016', 'user': 'planktonrules', 'rating': '7'}, {'title': 'Indiana Jones and the Last Crusade', 'year': '1989', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Gran Torino', 'year': '2008', 'user': 'planktonrules', 'rating': '10'}, {'title': 'Full Metal Jacket', 'year': '1987', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Aliens', 'year': '1986', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Amélie', 'year': '2001', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Guardians of the Galaxy: Vol. 2', 'year': '2017', 'user': 'planktonrules', 'rating': '6'}, {'title': 'John Wick', 'year': '2014', 'user': 'planktonrules', 'rating': '7'}, {'title': 'Get Out', 'year': '2017', 'user': 'planktonrules', 'rating': '9'}, {'title': 'The Social Network', 'year': '2010', 'user': 'planktonrules', 'rating': '7'}, {'title': 'Life Is Beautiful', 'year': '1997', 'user': 'planktonrules', 'rating': '10'}, {'title': 'Shrek', 'year': '2001', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Dunkirk', 'year': '2017', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Heat', 'year': '1995', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Spider-Man: Into the Spider-Verse', 'year': '2018', 'user': 'planktonrules', 'rating': '10'}, {'title': 'Fargo', 'year': '1996', 'user': 'planktonrules', 'rating': '8'}, {'title': '12 Years a Slave', 'year': '2013', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Spider-Man 2', 'year': '2004', 'user': 'planktonrules', 'rating': '7'}, {'title': 'Psycho', 'year': '1960', 'user': 'planktonrules', 'rating': '10'}, {'title': '2001: A Space Odyssey', 'year': '1968', 'user': 'planktonrules', 'rating': '5'}, {'title': 'Kingsman: The Secret Service', 'year': '2014', 'user': 'planktonrules', 'rating': '7'}, {'title': 'The Hunger Games: Catching Fire', 'year': '2013', 'user': 'planktonrules', 'rating': '9'}, {'title': '1917', 'year': '2019', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Skyfall', 'year': '2012', 'user': 'planktonrules', 'rating': '7'}, {'title': 'Silver Linings Playbook', 'year': '2012', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Now You See Me', 'year': '2013', 'user': 'planktonrules', 'rating': '6'}, {'title': 'Apocalypse Now', 'year': '1979', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Trainspotting', 'year': '1996', 'user': 'planktonrules', 'rating': '3'}, {'title': 'The Amazing Spider-Man', 'year': '2012', 'user': 'planktonrules', 'rating': '6'}, {'title': 'Million Dollar Baby', 'year': '2004', 'user': 'planktonrules', 'rating': '10'}, {'title': 'La La Land', 'year': '2016', 'user': 'planktonrules', 'rating': '7'}, {'title': 'Drive', 'year': '2011', 'user': 'planktonrules', 'rating': '7'}, {'title': 'X-Men: First Class', 'year': '2011', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Dune: Part Two', 'year': '2024', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Squid Game', 'year': '2021–2025', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Rogue One: A Star Wars Story', 'year': '2016', 'user': 'planktonrules', 'rating': '8'}, {'title': 'District 9', 'year': '2009', 'user': 'planktonrules', 'rating': '9'}, {'title': "Pan's Labyrinth", 'year': '2006', 'user': 'planktonrules', 'rating': '6'}, {'title': 'The Curious Case of Benjamin Button', 'year': '2008', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Casino Royale', 'year': '2006', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Jaws', 'year': '1975', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Groundhog Day', 'year': '1993', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Wonder Woman', 'year': '2017', 'user': 'planktonrules', 'rating': '7'}, {'title': "The King's Speech", 'year': '2010', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Her', 'year': '2013', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Star Wars: Episode VIII - The Last Jedi', 'year': '2017', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Frozen', 'year': '2013', 'user': 'planktonrules', 'rating': '7'}, {'title': 'Coco', 'year': '2017', 'user': 'planktonrules', 'rating': '10'}, {'title': 'There Will Be Blood', 'year': '2007', 'user': 'planktonrules', 'rating': '7'}, {'title': 'Life of Pi', 'year': '2012', 'user': 'planktonrules', 'rating': '8'}, {'title': 'It', 'year': '2017', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Birdman or (The Unexpected Virtue of Ignorance)', 'year': '2014', 'user': 'planktonrules', 'rating': '6'}, {'title': 'Superbad', 'year': '2007', 'user': 'planktonrules', 'rating': '1'}, {'title': 'Into the Wild', 'year': '2007', 'user': 'planktonrules', 'rating': '7'}, {'title': 'Rocky', 'year': '1976', 'user': 'planktonrules', 'rating': '10'}, {'title': 'Barbie', 'year': '2023', 'user': 'planktonrules', 'rating': '7'}, {'title': 'Tenet', 'year': '2020', 'user': 'planktonrules', 'rating': '4'}, {'title': 'Baby Driver', 'year': '2017', 'user': 'planktonrules', 'rating': '7'}, {'title': '12 Monkeys', 'year': '1995', 'user': 'planktonrules', 'rating': '6'}, {'title': 'Zodiac', 'year': '2007', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Toy Story 2', 'year': '1999', 'user': 'planktonrules', 'rating': '10'}, {'title': 'Nightcrawler', 'year': '2014', 'user': 'planktonrules', 'rating': '10'}, {'title': 'Zombieland', 'year': '2009', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Argo', 'year': '2012', 'user': 'planktonrules', 'rating': '10'}, {'title': 'Captain Marvel', 'year': '2019', 'user': 'planktonrules', 'rating': '8'}, {'title': 'L.A. Confidential', 'year': '1997', 'user': 'planktonrules', 'rating': '6'}, {'title': 'Casablanca', 'year': '1942', 'user': 'planktonrules', 'rating': '10'}, {'title': 'Lock, Stock and Two Smoking Barrels', 'year': '1998', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Everything Everywhere All at Once', 'year': '2022', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Bohemian Rhapsody', 'year': '2018', 'user': 'planktonrules', 'rating': '8'}, {'title': '21 Jump Street', 'year': '2012', 'user': 'planktonrules', 'rating': '7'}, {'title': 'Shaun of the Dead', 'year': '2004', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Zootopia', 'year': '2016', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Star Trek', 'year': '2009', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Despicable Me', 'year': '2010', 'user': 'planktonrules', 'rating': '8'}, {'title': 'The Pursuit of Happyness', 'year': '2006', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Casino', 'year': '1995', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Kick-Ass', 'year': '2010', 'user': 'planktonrules', 'rating': '7'}, {'title': 'The Bourne Identity', 'year': '2002', 'user': 'planktonrules', 'rating': '7'}, {'title': 'Three Billboards Outside Ebbing, Missouri', 'year': '2017', 'user': 'planktonrules', 'rating': '6'}, {'title': 'Monty Python and the Holy Grail', 'year': '1975', 'user': 'planktonrules', 'rating': '10'}, {'title': 'The Perks of Being a Wallflower', 'year': '2012', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Band of Brothers', 'year': '2001', 'user': 'planktonrules', 'rating': '10'}, {'title': 'Rain Man', 'year': '1988', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Source Code', 'year': '2011', 'user': 'planktonrules', 'rating': '10'}, {'title': 'Kung Fu Panda', 'year': '2008', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Love Actually', 'year': '2003', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Ford v Ferrari', 'year': '2019', 'user': 'planktonrules', 'rating': '6'}, {'title': 'Juno', 'year': '2007', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Charlie and the Chocolate Factory', 'year': '2005', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Indiana Jones and the Temple of Doom', 'year': '1984', 'user': 'planktonrules', 'rating': '3'}, {'title': 'Rear Window', 'year': '1954', 'user': 'planktonrules', 'rating': '9'}, {'title': 'X-Men Origins: Wolverine', 'year': '2009', 'user': 'planktonrules', 'rating': '4'}, {'title': 'Hot Fuzz', 'year': '2007', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Children of Men', 'year': '2006', 'user': 'planktonrules', 'rating': '8'}, {'title': 'The Incredible Hulk', 'year': '2008', 'user': 'planktonrules', 'rating': '6'}, {'title': 'The Maze Runner', 'year': '2014', 'user': 'planktonrules', 'rating': '3'}, {'title': 'Rush', 'year': '2013', 'user': 'planktonrules', 'rating': '7'}, {'title': 'Little Miss Sunshine', 'year': '2006', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Pacific Rim', 'year': '2013', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Big Hero 6', 'year': '2014', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Top Gun', 'year': '1986', 'user': 'planktonrules', 'rating': '3'}, {'title': "It's a Wonderful Life", 'year': '1946', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb', 'year': '1964', 'user': 'planktonrules', 'rating': '10'}, {'title': 'Dark', 'year': '2017–2020', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Dallas Buyers Club', 'year': '2013', 'user': 'planktonrules', 'rating': '6'}, {'title': 'The Hunger Games: Mockingjay - Part 1', 'year': '2014', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Tangled', 'year': '2010', 'user': 'planktonrules', 'rating': '10'}, {'title': 'The Fifth Element', 'year': '1997', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Star Wars: Episode IX - The Rise of Skywalker', 'year': '2019', 'user': 'planktonrules', 'rating': '5'}, {'title': 'The Big Short', 'year': '2015', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Cars', 'year': '2006', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Spotlight', 'year': '2015', 'user': 'planktonrules', 'rating': '10'}, {'title': 'Spider-Man: Across the Spider-Verse', 'year': '2023', 'user': 'planktonrules', 'rating': '4'}, {'title': 'Lost in Translation', 'year': '2003', 'user': 'planktonrules', 'rating': '3'}, {'title': 'Warrior', 'year': '2011', 'user': 'planktonrules', 'rating': '6'}, {'title': 'The Help', 'year': '2011', 'user': 'planktonrules', 'rating': '8'}, {'title': 'The Thing', 'year': '1982', 'user': 'planktonrules', 'rating': '5'}, {'title': 'Glass Onion', 'year': '2022', 'user': 'planktonrules', 'rating': '6'}, {'title': 'Mystic River', 

                          title  year           user rating
0      The Shawshank Redemption  1994  planktonrules     10
1               The Dark Knight  2008  planktonrules      9
2                     Inception  2010  planktonrules      8
3                    Fight Club  1999  planktonrules      6
4                  Interstellar  2014  planktonrules      8
..                          ...   ...            ...    ...
745  Ace Ventura: Pet Detective  1994     mark.waltz      1
746            The Untouchables  1987     mark.waltz      9
747                      Alien³  1992     mark.waltz      5
748                   Moonlight  2016     mark.waltz     10
749  O Brother, Where Art Thou?  2000     mark.waltz     10

[750 rows x 4 columns]

In [ ]:
# Attempts to get reviews of 250 most popular movies from every user in usr_links
for person in usr_links:
    try:
        dfu=user_rev_250(person)
        print(dfu)
        big_df=pd.concat([big_df,dfu], ignore_index=True)
    except:
        continue

big_df

[{'title': 'The Shawshank Redemption', 'year': '1994', 'user': 'planktonrules', 'rating': '10'}, {'title': 'The Dark Knight', 'year': '2008', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Inception', 'year': '2010', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Fight Club', 'year': '1999', 'user': 'planktonrules', 'rating': '6'}, {'title': 'Interstellar', 'year': '2014', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Forrest Gump', 'year': '1994', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Pulp Fiction', 'year': '1994', 'user': 'planktonrules', 'rating': '10'}, {'title': 'The Matrix', 'year': '1999', 'user': 'planktonrules', 'rating': '7'}, {'title': 'The Godfather', 'year': '1972', 'user': 'planktonrules', 'rating': '10'}, {'title': 'The Lord of the Rings: The Fellowship of the Ring', 'year': '2001', 'user': 'planktonrules', 'rating': '10'}, {'title': 'The Lord of the Rings: The Return of the King', 'year': '2003', 'user': 'planktonrules', 'rating': '10'}, {'title': 'Seven', 'year': '1995', 'user': 'planktonrules', 'rating': '9'}, {'title': 'The Dark Knight Rises', 'year': '2012', 'user': 'planktonrules', 'rating': '7'}, {'title': 'The Lord of the Rings: The Two Towers', 'year': '2002', 'user': 'planktonrules', 'rating': '10'}, {'title': 'Django Unchained', 'year': '2012', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Gladiator', 'year': '2000', 'user': 'planktonrules', 'rating': '8'}, {'title': 'The Wolf of Wall Street', 'year': '2013', 'user': 'planktonrules', 'rating': '5'}, {'title': 'Inglourious Basterds', 'year': '2009', 'user': 'planktonrules', 'rating': '8'}, {'title': 'The Silence of the Lambs', 'year': '1991', 'user': 'planktonrules', 'rating': '7'}, {'title': 'Batman Begins', 'year': '2005', 'user': 'planktonrules', 'rating': '7'}, {'title': 'Stranger Things', 'year': '2016–2025', 'user': 'planktonrules', 'rating': '10'}, {'title': 'Shutter Island', 'year': '2010', 'user': 'planktonrules', 'rating': '9'}, {'title': 'The Prestige', 'year': '2006', 'user': 'planktonrules', 'rating': '7'}, {'title': "Schindler's List", 'year': '1993', 'user': 'planktonrules', 'rating': '10'}, {'title': 'Star Wars: Episode IV - A New Hope', 'year': '1977', 'user': 'planktonrules', 'rating': '10'}, {'title': 'The Avengers', 'year': '2012', 'user': 'planktonrules', 'rating': '7'}, {'title': 'The Departed', 'year': '2006', 'user': 'planktonrules', 'rating': '7'}, {'title': 'Star Wars: Episode V - The Empire Strikes Back', 'year': '1980', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Avatar', 'year': '2009', 'user': 'planktonrules', 'rating': '9'}, {'title': 'The Godfather Part II', 'year': '1974', 'user': 'planktonrules', 'rating': '10'}, {'title': 'Back to the Future', 'year': '1985', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Memento', 'year': '2000', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Titanic', 'year': '1997', 'user': 'planktonrules', 'rating': '9'}, {'title': 'GoodFellas', 'year': '1990', 'user': 'planktonrules', 'rating': '4'}, {'title': 'The Truman Show', 'year': '1998', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Guardians of the Galaxy', 'year': '2014', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Léon: The Professional', 'year': '1994', 'user': 'planktonrules', 'rating': '7'}, {'title': 'WALL·E', 'year': '2008', 'user': 'planktonrules', 'rating': '7'}, {'title': 'Kill Bill: Vol. 1', 'year': '2003', 'user': 'planktonrules', 'rating': '10'}, {'title': 'Terminator 2: Judgment Day', 'year': '1991', 'user': 'planktonrules', 'rating': '9'}, {'title': 'American Beauty', 'year': '1999', 'user': 'planktonrules', 'rating': '8'}, {'title': 'American History X', 'year': '1998', 'user': 'planktonrules', 'rating': '9'}, {'title': 'The Lion King', 'year': '1994', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Deadpool', 'year': '2016', 'user': 'planktonrules', 'rating': '7'}, {'title': 'V for Vendetta', 'year': '2005', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Catch Me If You Can', 'year': '2002', 'user': 'planktonrules', 'rating': '7'}, {'title': 'The Usual Suspects', 'year': '1995', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Up', 'year': '2009', 'user': 'planktonrules', 'rating': '10'}, {'title': 'The Shining', 'year': '1980', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Iron Man', 'year': '2008', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Good Will Hunting', 'year': '1997', 'user': 'planktonrules', 'rating': '5'}, {'title': 'Star Wars: Episode VI - Return of the Jedi', 'year': '1983', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Finding Nemo', 'year': '2003', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Mad Max: Fury Road', 'year': '2015', 'user': 'planktonrules', 'rating': '8'}, {'title': 'No Country for Old Men', 'year': '2007', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Eternal Sunshine of the Spotless Mind', 'year': '2004', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Jurassic Park', 'year': '1993', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Toy Story', 'year': '1995', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Gone Girl', 'year': '2014', 'user': 'planktonrules', 'rating': '7'}, {'title': 'Parasite', 'year': '2019', 'user': 'planktonrules', 'rating': '6'}, {'title': 'Reservoir Dogs', 'year': '1992', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Braveheart', 'year': '1995', 'user': 'planktonrules', 'rating': '7'}, {'title': 'Whiplash', 'year': '2014', 'user': 'planktonrules', 'rating': '9'}, {'title': "One Flew Over the Cuckoo's Nest", 'year': '1975', 'user': 'planktonrules', 'rating': '10'}, {'title': 'The Sixth Sense', 'year': '1999', 'user': 'planktonrules', 'rating': '10'}, {'title': 'Raiders of the Lost Ark', 'year': '1981', 'user': 'planktonrules', 'rating': '9'}, {'title': 'The Hunger Games', 'year': '2012', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Monsters, Inc.', 'year': '2001', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Alien', 'year': '1979', 'user': 'planktonrules', 'rating': '10'}, {'title': 'Dune: Part One', 'year': '2021', 'user': 'planktonrules', 'rating': '7'}, {'title': 'A Beautiful Mind', 'year': '2001', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Oppenheimer', 'year': '2023', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Die Hard', 'year': '1988', 'user': 'planktonrules', 'rating': '9'}, {'title': 'The Intouchables', 'year': '2011', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Taxi Driver', 'year': '1976', 'user': 'planktonrules', 'rating': '5'}, {'title': 'Star Wars: Episode VII - The Force Awakens', 'year': '2015', 'user': 'planktonrules', 'rating': '10'}, {'title': 'Scarface', 'year': '1983', 'user': 'planktonrules', 'rating': '3'}, {'title': 'The Martian', 'year': '2015', 'user': 'planktonrules', 'rating': '10'}, {'title': 'The Terminator', 'year': '1984', 'user': 'planktonrules', 'rating': '10'}, {'title': '12 Angry Men', 'year': '1957', 'user': 'planktonrules', 'rating': '10'}, {'title': 'Snatch', 'year': '2000', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Requiem for a Dream', 'year': '2000', 'user': 'planktonrules', 'rating': '10'}, {'title': 'Toy Story 3', 'year': '2010', 'user': 'planktonrules', 'rating': '8'}, {'title': 'The Grand Budapest Hotel', 'year': '2014', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Spirited Away', 'year': '2001', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Captain America: The First Avenger', 'year': '2011', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Iron Man 3', 'year': '2013', 'user': 'planktonrules', 'rating': '7'}, {'title': 'Thor', 'year': '2011', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Once Upon a Time in... Hollywood', 'year': '2019', 'user': 'planktonrules', 'rating': '6'}, {'title': 'Ratatouille', 'year': '2007', 'user': 'planktonrules', 'rating': '10'}, {'title': 'Iron Man 2', 'year': '2010', 'user': 'planktonrules', 'rating': '5'}, {'title': 'Prisoners', 'year': '2013', 'user': 'planktonrules', 'rating': '10'}, {'title': 'A Clockwork Orange', 'year': '1971', 'user': 'planktonrules', 'rating': '7'}, {'title': 'The Hangover', 'year': '2009', 'user': 'planktonrules', 'rating': '3'}, {'title': 'Star Wars: Episode III - Revenge of the Sith', 'year': '2005', 'user': 'planktonrules', 'rating': '4'}, {'title': 'Inside Out', 'year': '2015', 'user': 'planktonrules', 'rating': '9'}, {'title': 'The Big Lebowski', 'year': '1998', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Donnie Darko', 'year': '2001', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Black Panther', 'year': '2018', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Slumdog Millionaire', 'year': '2008', 'user': 'planktonrules', 'rating': '9'}, {'title': 'The Incredibles', 'year': '2004', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Gravity', 'year': '2013', 'user': 'planktonrules', 'rating': '10'}, {'title': 'How to Train Your Dragon', 'year': '2010', 'user': 'planktonrules', 'rating': '10'}, {'title': 'The Good, the Bad and the Ugly', 'year': '1966', 'user': 'planktonrules', 'rating': '10'}, {'title': 'Black Swan', 'year': '2010', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Blade Runner', 'year': '1982', 'user': 'planktonrules', 'rating': '6'}, {'title': 'Knives Out', 'year': '2019', 'user': 'planktonrules', 'rating': '9'}, {'title': 'I Am Legend', 'year': '2007', 'user': 'planktonrules', 'rating': '6'}, {'title': 'City of God', 'year': '2002', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Kill Bill: Vol. 2', 'year': '2004', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Arrival', 'year': '2016', 'user': 'planktonrules', 'rating': '7'}, {'title': 'Indiana Jones and the Last Crusade', 'year': '1989', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Gran Torino', 'year': '2008', 'user': 'planktonrules', 'rating': '10'}, {'title': 'Full Metal Jacket', 'year': '1987', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Aliens', 'year': '1986', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Amélie', 'year': '2001', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Guardians of the Galaxy: Vol. 2', 'year': '2017', 'user': 'planktonrules', 'rating': '6'}, {'title': 'John Wick', 'year': '2014', 'user': 'planktonrules', 'rating': '7'}, {'title': 'Get Out', 'year': '2017', 'user': 'planktonrules', 'rating': '9'}, {'title': 'The Social Network', 'year': '2010', 'user': 'planktonrules', 'rating': '7'}, {'title': 'Life Is Beautiful', 'year': '1997', 'user': 'planktonrules', 'rating': '10'}, {'title': 'Shrek', 'year': '2001', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Dunkirk', 'year': '2017', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Heat', 'year': '1995', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Spider-Man: Into the Spider-Verse', 'year': '2018', 'user': 'planktonrules', 'rating': '10'}, {'title': 'Fargo', 'year': '1996', 'user': 'planktonrules', 'rating': '8'}, {'title': '12 Years a Slave', 'year': '2013', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Spider-Man 2', 'year': '2004', 'user': 'planktonrules', 'rating': '7'}, {'title': 'Psycho', 'year': '1960', 'user': 'planktonrules', 'rating': '10'}, {'title': '2001: A Space Odyssey', 'year': '1968', 'user': 'planktonrules', 'rating': '5'}, {'title': 'Kingsman: The Secret Service', 'year': '2014', 'user': 'planktonrules', 'rating': '7'}, {'title': 'The Hunger Games: Catching Fire', 'year': '2013', 'user': 'planktonrules', 'rating': '9'}, {'title': '1917', 'year': '2019', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Skyfall', 'year': '2012', 'user': 'planktonrules', 'rating': '7'}, {'title': 'Silver Linings Playbook', 'year': '2012', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Now You See Me', 'year': '2013', 'user': 'planktonrules', 'rating': '6'}, {'title': 'Apocalypse Now', 'year': '1979', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Trainspotting', 'year': '1996', 'user': 'planktonrules', 'rating': '3'}, {'title': 'The Amazing Spider-Man', 'year': '2012', 'user': 'planktonrules', 'rating': '6'}, {'title': 'Million Dollar Baby', 'year': '2004', 'user': 'planktonrules', 'rating': '10'}, {'title': 'La La Land', 'year': '2016', 'user': 'planktonrules', 'rating': '7'}, {'title': 'Drive', 'year': '2011', 'user': 'planktonrules', 'rating': '7'}, {'title': 'X-Men: First Class', 'year': '2011', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Dune: Part Two', 'year': '2024', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Squid Game', 'year': '2021–2025', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Rogue One: A Star Wars Story', 'year': '2016', 'user': 'planktonrules', 'rating': '8'}, {'title': 'District 9', 'year': '2009', 'user': 'planktonrules', 'rating': '9'}, {'title': "Pan's Labyrinth", 'year': '2006', 'user': 'planktonrules', 'rating': '6'}, {'title': 'The Curious Case of Benjamin Button', 'year': '2008', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Casino Royale', 'year': '2006', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Jaws', 'year': '1975', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Groundhog Day', 'year': '1993', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Wonder Woman', 'year': '2017', 'user': 'planktonrules', 'rating': '7'}, {'title': "The King's Speech", 'year': '2010', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Her', 'year': '2013', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Star Wars: Episode VIII - The Last Jedi', 'year': '2017', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Frozen', 'year': '2013', 'user': 'planktonrules', 'rating': '7'}, {'title': 'Coco', 'year': '2017', 'user': 'planktonrules', 'rating': '10'}, {'title': 'There Will Be Blood', 'year': '2007', 'user': 'planktonrules', 'rating': '7'}, {'title': 'Life of Pi', 'year': '2012', 'user': 'planktonrules', 'rating': '8'}, {'title': 'It', 'year': '2017', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Birdman or (The Unexpected Virtue of Ignorance)', 'year': '2014', 'user': 'planktonrules', 'rating': '6'}, {'title': 'Superbad', 'year': '2007', 'user': 'planktonrules', 'rating': '1'}, {'title': 'Into the Wild', 'year': '2007', 'user': 'planktonrules', 'rating': '7'}, {'title': 'Rocky', 'year': '1976', 'user': 'planktonrules', 'rating': '10'}, {'title': 'Barbie', 'year': '2023', 'user': 'planktonrules', 'rating': '7'}, {'title': 'Tenet', 'year': '2020', 'user': 'planktonrules', 'rating': '4'}, {'title': 'Baby Driver', 'year': '2017', 'user': 'planktonrules', 'rating': '7'}, {'title': '12 Monkeys', 'year': '1995', 'user': 'planktonrules', 'rating': '6'}, {'title': 'Zodiac', 'year': '2007', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Toy Story 2', 'year': '1999', 'user': 'planktonrules', 'rating': '10'}, {'title': 'Nightcrawler', 'year': '2014', 'user': 'planktonrules', 'rating': '10'}, {'title': 'Zombieland', 'year': '2009', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Argo', 'year': '2012', 'user': 'planktonrules', 'rating': '10'}, {'title': 'Captain Marvel', 'year': '2019', 'user': 'planktonrules', 'rating': '8'}, {'title': 'L.A. Confidential', 'year': '1997', 'user': 'planktonrules', 'rating': '6'}, {'title': 'Casablanca', 'year': '1942', 'user': 'planktonrules', 'rating': '10'}, {'title': 'Lock, Stock and Two Smoking Barrels', 'year': '1998', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Everything Everywhere All at Once', 'year': '2022', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Bohemian Rhapsody', 'year': '2018', 'user': 'planktonrules', 'rating': '8'}, {'title': '21 Jump Street', 'year': '2012', 'user': 'planktonrules', 'rating': '7'}, {'title': 'Shaun of the Dead', 'year': '2004', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Zootopia', 'year': '2016', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Star Trek', 'year': '2009', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Despicable Me', 'year': '2010', 'user': 'planktonrules', 'rating': '8'}, {'title': 'The Pursuit of Happyness', 'year': '2006', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Casino', 'year': '1995', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Kick-Ass', 'year': '2010', 'user': 'planktonrules', 'rating': '7'}, {'title': 'The Bourne Identity', 'year': '2002', 'user': 'planktonrules', 'rating': '7'}, {'title': 'Three Billboards Outside Ebbing, Missouri', 'year': '2017', 'user': 'planktonrules', 'rating': '6'}, {'title': 'Monty Python and the Holy Grail', 'year': '1975', 'user': 'planktonrules', 'rating': '10'}, {'title': 'The Perks of Being a Wallflower', 'year': '2012', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Band of Brothers', 'year': '2001', 'user': 'planktonrules', 'rating': '10'}, {'title': 'Rain Man', 'year': '1988', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Source Code', 'year': '2011', 'user': 'planktonrules', 'rating': '10'}, {'title': 'Kung Fu Panda', 'year': '2008', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Love Actually', 'year': '2003', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Ford v Ferrari', 'year': '2019', 'user': 'planktonrules', 'rating': '6'}, {'title': 'Juno', 'year': '2007', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Charlie and the Chocolate Factory', 'year': '2005', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Indiana Jones and the Temple of Doom', 'year': '1984', 'user': 'planktonrules', 'rating': '3'}, {'title': 'Rear Window', 'year': '1954', 'user': 'planktonrules', 'rating': '9'}, {'title': 'X-Men Origins: Wolverine', 'year': '2009', 'user': 'planktonrules', 'rating': '4'}, {'title': 'Hot Fuzz', 'year': '2007', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Children of Men', 'year': '2006', 'user': 'planktonrules', 'rating': '8'}, {'title': 'The Incredible Hulk', 'year': '2008', 'user': 'planktonrules', 'rating': '6'}, {'title': 'The Maze Runner', 'year': '2014', 'user': 'planktonrules', 'rating': '3'}, {'title': 'Rush', 'year': '2013', 'user': 'planktonrules', 'rating': '7'}, {'title': 'Little Miss Sunshine', 'year': '2006', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Pacific Rim', 'year': '2013', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Big Hero 6', 'year': '2014', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Top Gun', 'year': '1986', 'user': 'planktonrules', 'rating': '3'}, {'title': "It's a Wonderful Life", 'year': '1946', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb', 'year': '1964', 'user': 'planktonrules', 'rating': '10'}, {'title': 'Dark', 'year': '2017–2020', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Dallas Buyers Club', 'year': '2013', 'user': 'planktonrules', 'rating': '6'}, {'title': 'The Hunger Games: Mockingjay - Part 1', 'year': '2014', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Tangled', 'year': '2010', 'user': 'planktonrules', 'rating': '10'}, {'title': 'The Fifth Element', 'year': '1997', 'user': 'planktonrules', 'rating': '9'}, {'title': 'Star Wars: Episode IX - The Rise of Skywalker', 'year': '2019', 'user': 'planktonrules', 'rating': '5'}, {'title': 'The Big Short', 'year': '2015', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Cars', 'year': '2006', 'user': 'planktonrules', 'rating': '8'}, {'title': 'Spotlight', 'year': '2015', 'user': 'planktonrules', 'rating': '10'}, {'title': 'Spider-Man: Across the Spider-Verse', 'year': '2023', 'user': 'planktonrules', 'rating': '4'}, {'title': 'Lost in Translation', 'year': '2003', 'user': 'planktonrules', 'rating': '3'}, {'title': 'Warrior', 'year': '2011', 'user': 'planktonrules', 'rating': '6'}, {'title': 'The Help', 'year': '2011', 'user': 'planktonrules', 'rating': '8'}, {'title': 'The Thing', 'year': '1982', 'user': 'planktonrules', 'rating': '5'}, {'title': 'Glass Onion', 'year': '2022', 'user': 'planktonrules', 'rating': '6'}, {'title': 'Mystic River', 

                          title  year           user rating
0      The Shawshank Redemption  1994  planktonrules     10
1               The Dark Knight  2008  planktonrules      9
2                     Inception  2010  planktonrules      8
3                    Fight Club  1999  planktonrules      6
4                  Interstellar  2014  planktonrules      8
...                         ...   ...            ...    ...
17085                 Lady Bird  2017    TaylorYee94      7
17086                 Liar Liar  1997    TaylorYee94      5
17087            Les Misérables  2012    TaylorYee94      8
17088             Up in the Air  2009    TaylorYee94      8
17089      Beauty and the Beast  2017    TaylorYee94      8

[17090 rows x 4 columns]

In [ ]:
#exportas data frame into csv file
big_df.to_csv('imdb_data.csv')